### ISSUE TITLE
Bug: Media players cannot "seek" to a particular time on the recorded webm video

### ISSUE THREAD

**Issue by soumik-mukherjee** [soumik-mukherjee/capturio#34]
**Describe the bug**
Once you've recorded and download the file, and the open it offline, you are not able to "seek" to a particular time instant in the video, using the controls. 

This is irrespective of the player used to open the file offline, tried,
1. Chrome browser
2. Win 10 media player
3. Win 10 movies and TV app

**To Reproduce**
1. Click on 'Download' and save the recording locally
2. Double click to open on default app, or right click and choose open with
3. Player loads the file and plays it fine but seek on the time control does not work

**Expected behavior**
Users should be able to seek to a particular instant

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Win 10 64 bit
 - Browser : Chrome v81.0

**Additional context**
See related stuff on the internet:
1. [A related stackoverflow discussion](https://stackoverflow.com/questions/8088364/html5-video-will-not-loop/9549404#9549404)
2. [A related issue in another GH project](https://github.com/videojs/video.js/issues/1031)
3. [Another related GH repo issue](https://github.com/muaz-khan/Chrome-Extensions/issues/25)

**Comment by sundar505** [comment]
I am facing same issue. is there is any solution

**Comment by soumik-mukherjee** [comment]
> I am facing same issue. is there is any solution

Not yet @sundar505, I am led to believe that the problem is more to do with the media container, i.e. `webem`. However I am yet to confirm this.

**Comment by soumik-mukherjee** [comment]
> I am facing same issue. is there is any solution

@sundar505 tested with the following today and the seek works fine. Maybe this workaround will work for you:

1. OS : Ubuntu 20.04.1 LTS, 64 Bit
2. Gnome: 3.36.3
3. Browser (the running the app to record): Chrome Version 84.0.4147.125 (Official Build) (64-bit)
4. Browser (used to run the downloaded recording file, i.e. `webem`): Mozilla Firefox 79.0 (64-bit) (canonical build)

If you don't have a handy Ubuntu desktop, I suggest you trying playing the recording with Firefox once and see if the seek works (I suspect it wont) on whatever OS you are on.

If you can report back any findings, it will help me to solve the problem.

**Comment by sundar505** [comment]
@soumik-mukherjee Thanks. I solved the issue.

The issue is **Timerange metadata** ain't available in the Blob chunks recorded using mediarecorder API. I have re-encoded the chunks with Timerange metadata and its working fine in all browsers.

**Comment by soumik-mukherjee** [comment]
Thanks @sundar505. Would you like to put up a PR?

**Comment by michaelruther95** [comment]
> Timerange metadata

do you have a sample code that we could use?

**Comment by taimoorkhokhar** [comment]
The following code worked for me it injects the missing metadata and saves a seekable webm file.

`const {Decoder, Encoder, tools, Reader} = require("ts-ebml");

const injectMetadata = function(blob) {
      const decoder = new Decoder();
      const reader = new Reader();
      reader.logging = false;
      reader.drop_default_duration = false;

      return readAsArrayBuffer(blob).then((buffer) => {
        const elms = decoder.decode(buffer);
        elms.forEach((elm) => {
          reader.read(elm);
        });
        reader.stop();

        const refinedMetadataBuf = tools.makeMetadataSeekable(
          reader.metadatas, reader.duration, reader.cues);
        const body = buffer.slice(reader.metadataSize);

        const result = new Blob([refinedMetadataBuf, body], {
          type: blob.type
        });
        result.arrayBuffer().then((arrayBuffer) => {
          const buffer = Buffer.from(arrayBuffer);
          fs.writeFile("seekable_new.webm", buffer, () => {
            console.log("video saved");
          });
        });
        

        return result;
      });
    }`

**Comment by taimoorkhokhar** [comment]
The following code worked for me. Hope this helps! :)

```
const injectMetadata = function(blob) {
      const decoder = new Decoder();
      const reader = new Reader();
      reader.logging = false;
      reader.drop_default_duration = false;

      return readAsArrayBuffer(blob).then((buffer) => {
        const elms = decoder.decode(buffer);
        elms.forEach((elm) => {
          reader.read(elm);
        });
        reader.stop();

        const refinedMetadataBuf = tools.makeMetadataSeekable(
          reader.metadatas, reader.duration, reader.cues);
        const body = buffer.slice(reader.metadataSize);

        const result = new Blob([refinedMetadataBuf, body], {
          type: blob.type
        });
        result.arrayBuffer().then((arrayBuffer) => {
          const buffer = Buffer.from(arrayBuffer);
          fs.writeFile("seekable_new.webm", buffer, () => {
            console.log("video saved");
          });
        });
        

        return result;
      });
    }```

**Comment by taimoorkhokhar** [comment]
The following code worked for me. Hope this helps! :)

```
const {Decoder, Encoder, tools, Reader} = require("ts-ebml");

const injectMetadata = function(blob) {
      const decoder = new Decoder();
      const reader = new Reader();
      reader.logging = false;
      reader.drop_default_duration = false;

      return readAsArrayBuffer(blob).then((buffer) => {
        const elms = decoder.decode(buffer);
        elms.forEach((elm) => {
          reader.read(elm);
        });
        reader.stop();

        const refinedMetadataBuf = tools.makeMetadataSeekable(
          reader.metadatas, reader.duration, reader.cues);
        const body = buffer.slice(reader.metadataSize);

        const result = new Blob([refinedMetadataBuf, body], {
          type: blob.type
        });
        result.arrayBuffer().then((arrayBuffer) => {
          const buffer = Buffer.from(arrayBuffer);
          fs.writeFile("seekable_new.webm", buffer, () => {
            console.log("video saved");
          });
        });
        

        return result;
      });
    }

```

**Comment by stutirastogi** [comment]
Is there any stable solution for this? or how about utilizing any framework other than mediarecorder?

**Comment by sundar505** [comment]
@stutirastogi You can use this lib, https://recordrtc.org/

this has inbuilt function to solve this problem
